name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  nodejs:
    uses: zakodium/workflows/.github/workflows/nodejs.yml@nodejs-v1
    with:
      lint-check-types: true
      upload-coverage: true
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
