name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  nodejs:
    uses: zakodium/workflows/.github/workflows/nodejs.yml@secrets-env
    with:
      lint-check-types: true
    secrets:
      ENV_TEST: ${{ secrets.TEST }}
